Repository nimiq/core-rs-albatross, pull requests merged in 2022-05, with the labels that each got.

#840 Fix oldest transaction ordering in mempool
  mempool/src/mempool.rs
Labels: WIP

#851 RPC: Move get_transaction_by_hash function from mempool into blockchain dispatcher
  rpc-interface/src/blockchain.rs
  rpc-interface/src/mempool.rs
  rpc-server/src/dispatchers/blockchain.rs
  rpc-server/src/dispatchers/mempool.rs
Labels: refactor

#865 Serialize Signatures to HEX for display and JSON
  keys/src/signature.rs
Labels: enhancement
