Repository nimiq/core-rs-albatross, pull requests merged in 2023-03, with the labels that each got.

#1430 Adapt arguments of getTransactionsByAddress to be 1.0-compatible
  consensus/src/consensus/consensus_proxy.rs
  web-client/src/lib.rs
  web-client/src/transaction.rs
Labels: WASM

#1239 Cud4m/remove log rotation and fix log
  Cargo.lock
  lib/Cargo.toml
  lib/src/config/config_file/client.example.toml
  lib/src/config/config_file/mod.rs
  lib/src/extras/logging.rs
Labels: bug

#1237 Prune epoch doesn't remove *all* micro blocks
  blockchain/src/chain_store.rs
  blockchain/tests/mod.rs
Labels: bug

#1409 Don't precompute Pedersen hashes
  Cargo.lock
  zkp-circuits/src/gadgets/mnt6/state_commitment.rs
  zkp-circuits/src/gadgets/mnt6/vk_commitment.rs
  zkp-circuits/src/gadgets/pedersen.rs
  zkp-primitives/Cargo.toml
  zkp-primitives/build.rs
  zkp-primitives/pedersen-generators/Cargo.toml
  zkp-primitives/pedersen-generators/benches/generate.rs
  zkp-primitives/pedersen-generators/src/generators.rs
  zkp-primitives/pedersen-generators/src/lib.rs
  zkp-primitives/pedersen-generators/src/serialization.rs
  zkp-primitives/src/lib.rs
  zkp-primitives/src/pedersen.rs
  zkp-primitives/src/pedersen_generator_powers.rs
Labels: WASM

#1443 ZKP Fixes
  .gitignore
  .zkp/verifying_keys/merger_wrapper.bin
  Cargo.lock
  Cargo.toml
  block-production/src/test_custom_block.rs
  blockchain-proxy/src/blockchain_proxy.rs
  blockchain/src/blockchain/verify.rs
  blockchain/tests/signed.rs
  light-blockchain/src/sync.rs
  primitives/block/src/macro_block.rs
  primitives/block/src/micro_block.rs
  primitives/block/src/tendermint.rs
  test-utils/src/block_production.rs
  test-utils/src/blockchain.rs
  validator/src/aggregation/tendermint/proposal.rs
  validator/src/tendermint.rs
  zkp-circuits/src/circuits/mnt4/macro_block_wrapper.rs
  zkp-circuits/src/circuits/mnt4/merger_wrapper.rs
  zkp-circuits/src/circuits/mnt4/pk_tree_node.rs
  zkp-circuits/src/circuits/mnt6/macro_block.rs
  zkp-circuits/src/circuits/mnt6/merger.rs
  zkp-circuits/src/circuits/mnt6/pk_tree_leaf.rs
  zkp-circuits/src/circuits/mnt6/pk_tree_node.rs
  zkp-circuits/src/circuits/mod.rs
  zkp-circuits/src/gadgets/mnt6/merkle_tree.rs
  zkp-circuits/src/gadgets/mnt6/mod.rs
  zkp-circuits/src/gadgets/mnt6/state_commitment.rs
  zkp-circuits/src/gadgets/mnt6/vk_commitment.rs
  zkp-circuits/src/gadgets/mod.rs
  zkp-circuits/src/gadgets/pedersen.rs
  zkp-circuits/src/gadgets/recursive_input.rs
  zkp-circuits/src/lib.rs
  zkp-circuits/src/setup.rs
  zkp-circuits/src/utils.rs
  zkp-primitives/pedersen-generators/src/generators.rs
  zkp-primitives/src/macro_block.rs
  zkp-primitives/src/pedersen.rs
  zkp/Cargo.toml
  zkp/README.md
  zkp/examples/prover/prove.rs
  zkp/examples/prover/setup.rs
  zkp/images/light_node.drawio
  zkp/images/light_node.png
  zkp/src/lib.rs
  zkp/src/proof_system/mod.rs
  zkp/src/proof_system/prove.rs
  zkp/src/proof_system/verify.rs
  zkp/tests/prover/recursive_input.rs
Labels: bug

#1448 Rename `include_transactions` to `include_body` in RPC server, interface and client
  rpc-client/src/subcommands/blockchain_subcommands.rs
  rpc-interface/src/blockchain.rs
  rpc-interface/src/types.rs
  rpc-server/src/dispatchers/blockchain.rs
Labels: enhancement

#1410 Serialize blocks to JS as objects
  Cargo.lock
  web-client/Cargo.toml
  web-client/module.js
  web-client/src/block.rs
  web-client/src/lib.rs
Labels: WASM

#1461 Make the web-client's network ID configurable
  web-client/src/lib.rs
Labels: WASM

#1460 Emit "syncing" consensus events
  web-client/src/lib.rs
Labels: WASM

#1476 Remove panic when requesting unknown block via RPC
  rpc-interface/src/types.rs
  rpc-server/src/dispatchers/blockchain.rs
Labels: bug

#1490 Fix generation of devnet keys in prover
  lib/src/client.rs
  zkp/src/proof_system/prove.rs
Labels: bug

#1498 Compat for WASM PrivateKey, PublicKey & KeyPair APIs
  web-client/src/key_pair.rs
  web-client/src/private_key.rs
  web-client/src/public_key.rs
Labels: WASM

#1504 Fetching all stakers from a validator
  consensus/src/consensus/consensus_proxy.rs
  keys/src/address.rs
  primitives/account/src/account/staking_contract/mod.rs
  primitives/account/src/account/staking_contract/store.rs
  primitives/account/src/data_store.rs
  primitives/account/src/data_store_ops.rs
  primitives/account/tests/staking_contract.rs
  primitives/src/key_nibbles.rs
  primitives/trie/src/trie.rs
  rpc-client/src/subcommands/blockchain_subcommands.rs
  rpc-interface/src/blockchain.rs
  rpc-interface/src/types.rs
  rpc-server/src/dispatchers/blockchain.rs
  validator/tests/mock.rs
Labels: bug

#1510 Fixing panic when calculating the upper bound
  consensus/src/sync/light/sync_stream.rs
Labels: bug

#1513 Increasing macro sync threshold to a epoch
  consensus/src/sync/light/sync.rs
  consensus/src/sync/light/sync_stream.rs
  consensus/src/sync/syncer_proxy.rs
  consensus/tests/sync_utils.rs
  lib/src/client.rs
  primitives/account/src/account/staking_contract/validator.rs
Labels: enhancement

#1516 consensus: Drop the blockchain lock ASAP for live block queue
  consensus/src/sync/live/block_queue/mod.rs
Labels: enhancement

#1518 Increase default buffer size in block queue
  consensus/src/sync/live/queue.rs
  consensus/src/sync/syncer_proxy.rs
Labels: enhancement

#1522 Release web-client NPM package
  web-client/Cargo.toml
  web-client/README.md
  web-client/dist/README.md
  web-client/dist/package.json
  web-client/module.js
  web-client/release.sh
Labels: WASM

#1527 Return missing blocks starting from lowest block
  consensus/src/consensus/mod.rs
  consensus/src/consensus/remote_event_dispatcher.rs
  consensus/src/error.rs
  consensus/src/lib.rs
  consensus/src/messages/handlers.rs
  consensus/src/messages/mod.rs
  consensus/src/sync/live/block_queue/block_request_component.rs
Labels: enhancement
