Repository nimiq/core-rs-albatross, pull requests merged in 2023-12, with the labels that each got.

#2020 network-libp2p: Re-implement request response codec
  network-libp2p/src/behaviour.rs
  network-libp2p/src/dispatch/codecs/mod.rs
  network-libp2p/src/dispatch/codecs/tokio_adapter.rs
  network-libp2p/src/dispatch/codecs/typed.rs
  network-libp2p/src/error.rs
  network-libp2p/src/network.rs
Labels: testnet-restart

#2039 Add fallen behind peers to the timeout collection as well.
  consensus/src/sync/syncer.rs
Labels: bug

#2003 Change policy constants
  primitives/src/policy.rs
  primitives/transaction/tests/staking_contract_verify.rs
Labels: testnet-restart

#2046 Updating the batches per epoch on devnet scenarios
  .github/workflows/devnet_scenarios.yml
Labels: bug, github_actions

#2053 Change staking contract transaction from set_inactive_stake to set_active_stake
  primitives/account/src/account/staking_contract/receipts.rs
  primitives/account/src/account/staking_contract/staker.rs
  primitives/account/src/account/staking_contract/traits.rs
  primitives/account/src/logs.rs
  primitives/account/tests/accounts.rs
  primitives/account/tests/staking_contract/mod.rs
  primitives/account/tests/staking_contract/staker.rs
  primitives/transaction/src/account/staking_contract/structs.rs
  rpc-client/src/subcommands/transactions_subcommands.rs
  rpc-interface/src/consensus.rs
  rpc-interface/src/types.rs
  rpc-server/src/dispatchers/consensus.rs
  test-utils/src/transactions.rs
  transaction-builder/src/lib.rs
  transaction-builder/src/recipient/staking_contract.rs
  web-client/src/primitives/transaction_builder.rs
  web-client/src/transaction.rs
Labels: enhancement, testnet-restart

#2071 Add missing fields in RPC transaction response
  rpc-interface/src/types.rs
Labels: bug
