Repository nimiq/core-rs-albatross, pull requests merged in 2023-11, with the labels that each got.

#1936 [RPC] Refactor Inherent Enum Serialization in types.rs
  rpc-interface/src/types.rs
Labels: enhancement

#1942 Finalize the first batch
  blockchain/src/blockchain/inherents.rs
Labels: bug

#1953 Fix comment in history chunk proof
  blockchain/src/history/history_store.rs
Labels: documentation

#1957 Correctly check the signer of the VRF seed for macro block proposals.
  blockchain/src/blockchain/verify.rs
Labels: bug

#1969 Penalize/Jail inherents are also necessary for history sync
  blockchain/src/blockchain/history_sync.rs
  primitives/transaction/src/historic_transaction.rs
  rpc-interface/src/types.rs
Labels: testnet-restart

#1955 Revert "Don't include the signatures in historic transactions"
  consensus/tests/consensus_proxy.rs
  primitives/transaction/src/historic_transaction.rs
Labels: testnet-restart

#2002 Fix transaction builder docs
  transaction-builder/src/lib.rs
  transaction-builder/src/proof/mod.rs
  transaction-builder/src/recipient/staking_contract.rs
Labels: documentation
