Repository nimiq/core-rs-albatross, pull requests merged in 2023-07, with the labels that each got.

#1708 Parse HistoryStore's last_leaf_table key from big endian for usage
  blockchain/src/history/history_store.rs
Labels: bug

#1723 Removing old and unused return types for logs
  primitives/account/src/logs.rs
Labels: enhancement

#1694 blockchain: Do not create zero value reward transactions
  blockchain/src/blockchain/inherents.rs
Labels: enhancement, testnet-restart

#1710 History store integer keys
  blockchain/src/history/history_store.rs
Labels: enhancement, testnet-restart

#1709 Serialize MerklePath to one byte when empty
  primitives/transaction/tests/serialization.rs
  primitives/transaction/tests/staking_contract_verify.rs
  utils/src/merkle/mod.rs
  utils/tests/merkle/mod.rs
Labels: testnet-restart, regression

#1720 Remove the print of private keys for config
  lib/src/config/config.rs
  lib/src/config/config_file/mod.rs
Labels: enhancement

#1724 Adding tests for pushing zkps
  blockchain/tests/push.rs
  light-blockchain/tests/push.rs
Labels: enhancement

#1719 Fix SizeProof in MMR and add tests
  blockchain/src/history/history_store.rs
  primitives/mmr/src/mmr/mod.rs
  primitives/mmr/src/mmr/proof.rs
  primitives/mmr/src/mmr/utils.rs
Labels: enhancement

#1717 transaction: Make the hash compatible with PoW
  primitives/transaction/src/lib.rs
  primitives/transaction/tests/staking_contract_verify.rs
Labels: testnet-restart

#1685 Use sender_data for outgoing staking contract details instead of proof
  primitives/account/src/account/staking_contract/traits.rs
  primitives/account/src/logs.rs
  primitives/account/tests/htlc_contract.rs
  primitives/account/tests/staking_contract/mod.rs
  primitives/account/tests/staking_contract/staker.rs
  primitives/account/tests/staking_contract/validator.rs
  primitives/account/tests/vesting_contract.rs
  primitives/transaction/src/account/htlc_contract.rs
  primitives/transaction/src/account/staking_contract/mod.rs
  primitives/transaction/src/account/staking_contract/structs.rs
  primitives/transaction/src/account/vesting_contract.rs
  primitives/transaction/src/lib.rs
  primitives/transaction/tests/basic_account_verify.rs
  primitives/transaction/tests/htlc_contract_verify.rs
  primitives/transaction/tests/serialization.rs
  primitives/transaction/tests/staking_contract_verify.rs
  primitives/transaction/tests/vesting_contract_verify.rs
  rpc-interface/src/types.rs
  test-utils/src/transactions.rs
  transaction-builder/src/lib.rs
  transaction-builder/src/proof/htlc_contract.rs
  transaction-builder/src/proof/mod.rs
  transaction-builder/src/proof/staking_contract.rs
  transaction-builder/src/sender.rs
  transaction-builder/tests/htlc_contract.rs
  transaction-builder/tests/staking_contract.rs
  transaction-builder/tests/vesting_contract.rs
  web-client/src/client/lib.rs
  web-client/src/primitives/transaction_builder.rs
  web-client/src/transaction.rs
Labels: testnet-restart

#1728 Add CI profile without incremental compilation
  .github/workflows/build+test.yml
  .github/workflows/code_coverage.yml
  .github/workflows/devnet_scenarios.yml
  Cargo.toml
Labels: enhancement
