Repository nimiq/core-rs-albatross, pull requests merged in 2023-06, with the labels that each got.

#1611 genesis: Reduce the stake of validators
  genesis/src/genesis/test-albatross.toml
Labels: testnet-restart

#1570 Fix timestamp of genesis block to be in milliseconds
  genesis-builder/src/lib.rs
Labels: bug, testnet-restart

#1571 Encode genesis supply in genesis block
  genesis-builder/src/lib.rs
Labels: bug, enhancement, testnet-restart

#1647 Remove parked state
  block-production/src/lib.rs
  block-production/src/test_custom_block.rs
  block-production/tests/mod.rs
  blockchain/src/blockchain/inherents.rs
  blockchain/src/blockchain/verify.rs
  blockchain/tests/inherents.rs
  mempool/tests/mod.rs
  metrics-server/src/chain.rs
  primitives/account/src/account/staking_contract/mod.rs
  primitives/account/src/account/staking_contract/receipts.rs
  primitives/account/src/account/staking_contract/traits.rs
  primitives/account/src/account/staking_contract/validator.rs
  primitives/account/src/logs.rs
  primitives/account/src/reserved_balance.rs
  primitives/account/tests/accounts.rs
  primitives/account/tests/staking_contract.rs
  primitives/transaction/src/account/staking_contract/structs.rs
  primitives/transaction/tests/staking_contract_verify.rs
  rpc-client/src/subcommands/blockchain_subcommands.rs
  rpc-client/src/subcommands/validator_subcommands.rs
  rpc-interface/src/blockchain.rs
  rpc-interface/src/consensus.rs
  rpc-interface/src/types.rs
  rpc-server/src/dispatchers/blockchain.rs
  rpc-server/src/dispatchers/consensus.rs
  test-utils/src/transactions.rs
  transaction-builder/src/lib.rs
  transaction-builder/src/recipient/mod.rs
  transaction-builder/src/recipient/staking_contract.rs
  transaction-builder/tests/staking_contract.rs
  validator/src/validator.rs
  web-client/src/account.rs
  web-client/src/transaction.rs
  web-client/src/transaction_builder.rs
Labels: enhancement
