Repository nimiq/core-rs-albatross, pull requests merged in 2023-02, with the labels that each got.

#1331 Fixing zkp-prover and parallel features always enabled
  Cargo.toml
  lib/Cargo.toml
  lib/src/client.rs
  lib/src/config/config.rs
  lib/src/config/config_file/mod.rs
  test-utils/src/node.rs
  zkp-circuits/Cargo.toml
  zkp-circuits/src/lib.rs
  zkp-circuits/src/setup.rs
  zkp-circuits/zkp-setup/main.rs
  zkp-component/Cargo.toml
  zkp-component/src/proof_gen_utils.rs
  zkp-component/src/prover_binary.rs
  zkp-component/src/types.rs
  zkp-component/src/zkp_component.rs
  zkp-component/src/zkp_prover.rs
  zkp-component/tests/types.rs
  zkp-component/tests/zkp_component.rs
  zkp/Cargo.toml
  zkp/build.rs
  zkp/src/nano_zkp/prove.rs
Labels: bug

#1338 network-libp2p: Improve the discovery behaviour
  lib/src/client.rs
  network-libp2p/src/connection_pool/behaviour.rs
  network-libp2p/src/discovery/behaviour.rs
  network-libp2p/src/discovery/handler.rs
  network-libp2p/src/discovery/peer_contacts.rs
  network-libp2p/src/lib.rs
  network-libp2p/src/network.rs
  network-libp2p/tests/request_response.rs
Labels: WIP

#1347 Avoiding duplicates in the pending for deletion rate limiting
  network-libp2p/src/network.rs
  network-libp2p/src/rate_limiting.rs
  network-libp2p/tests/request_response.rs
Labels: bug

#1351 Start state live sync as complete
  consensus/src/sync/live/state_queue/mod.rs
Labels: bug

#1350 Wasm-JS interactivity, part two: staking roundtrip
  Cargo.lock
  web-client/Cargo.toml
  web-client/module.js
  web-client/src/lib.rs
  web-client/src/transaction.rs
  web-client/src/transaction_builder.rs
Labels: WASM
