Repository nimiq/core-rs-albatross, pull requests merged in 2023-08, with the labels that each got.

#1734 Fixing code coverage
  consensus/tests/request_component.rs
  test-utils/src/test_network.rs
  validator/tests/integration.rs
  validator/tests/mock.rs
Labels: bug, github_actions

#1752 Fix mempool check for unstake
  primitives/account/src/account/staking_contract/staker.rs
  primitives/account/src/account/staking_contract/traits.rs
Labels: bug

#1750 blockchain: Fix verifying history setting for the genesis
  blockchain/src/blockchain/blockchain.rs
Labels: bug

#1755 Modify transaction struct itself when calling sign() on it
  web-client/example/module.js
  web-client/src/transaction.rs
Labels: WASM

#1762 Fix code coverage errors when freeing up space
  .github/workflows/code_coverage.yml
Labels: bug, github_actions

#1759 Allow to set inactive balance with the update-staker functionality
  primitives/account/src/account/staking_contract/receipts.rs
  primitives/account/src/account/staking_contract/staker.rs
  primitives/account/src/account/staking_contract/traits.rs
  primitives/account/src/logs.rs
  primitives/account/tests/staking_contract/mod.rs
  primitives/account/tests/staking_contract/staker.rs
  primitives/account/tests/staking_contract/validator.rs
  primitives/transaction/src/account/staking_contract/structs.rs
  primitives/transaction/tests/staking_contract_verify.rs
  rpc-client/src/subcommands/transactions_subcommands.rs
  rpc-interface/src/consensus.rs
  rpc-server/src/dispatchers/consensus.rs
  test-utils/src/transactions.rs
  transaction-builder/src/lib.rs
  transaction-builder/src/recipient/staking_contract.rs
  transaction-builder/tests/staking_contract.rs
  web-client/src/primitives/transaction_builder.rs
Labels: enhancement, testnet-restart

#1761 Use forked tsify branch to copy rustdoc comments over to web TS types
  Cargo.lock
  primitives/Cargo.toml
  primitives/transaction/Cargo.toml
  web-client/Cargo.toml
Labels: WASM

#1801 Update ZKP readme and images
  zkp-circuits/README.md
  zkp-circuits/images/light_node.drawio
  zkp-circuits/images/light_node.png
  zkp-circuits/images/merger_circuit.drawio
  zkp-circuits/images/merger_circuit.png
  zkp-circuits/images/pk_tree_circuit.drawio
  zkp-circuits/images/pk_tree_circuit.png
  zkp/README.md
  zkp/images/light_node.drawio
  zkp/images/light_node.png
  zkp/images/macro_block_circuit.drawio
  zkp/images/macro_block_circuit.png
  zkp/images/merger_circuit.drawio
  zkp/images/merger_circuit.png
  zkp/images/pk_tree_circuit.drawio
  zkp/images/pk_tree_circuit.png
  zkp/images/wrapper_circuit.drawio
  zkp/images/wrapper_circuit.png
Labels: enhancement
