Repository nimiq/core-rs-albatross, pull requests merged in 2024-12, with the labels that each got.

#3168 Fixing clippy warnings
  Cargo.lock
  blockchain-proxy/src/blockchain_proxy.rs
  blockchain/src/history/history_store.rs
  blockchain/src/history/history_store_index.rs
  blockchain/src/history/merged_history_store.rs
  blockchain/src/history/mmr_store.rs
  blockchain/tests/block_production.rs
  blockchain/tests/blockchain.rs
  blockchain/tests/history_store.rs
  blockchain/tests/merged_history_store.rs
  blockchain/tests/signed.rs
  consensus/src/sync/live/block_queue/assembler.rs
  database/benches/hash_keys.rs
  database/benches/pruning.rs
  database/src/mdbx/cursor.rs
  database/src/mdbx/iterators.rs
  hash/src/hmac.rs
  hash/src/lib.rs
  network-libp2p/tests/network.rs
  network-libp2p/tests/request_response.rs
  network-mock/src/lib.rs
  primitives/account/src/account/staking_contract/store.rs
  primitives/account/src/data_store.rs
  primitives/account/tests/accounts.rs
  primitives/block/tests/macro_block.rs
  primitives/mmr/src/store/memory.rs
  primitives/src/key_nibbles.rs
  primitives/src/policy.rs
  primitives/src/trie/trie_node.rs
  primitives/transaction/tests/serialization.rs
  primitives/trie/src/transaction.rs
  primitives/trie/src/trie.rs
  serde/src/lib.rs
  utils/tests/merkle/incremental.rs
  utils/tests/merkle/partial.rs
  validator-network/src/single_response_requester.rs
  validator/src/aggregation/tendermint/state.rs
  validator/tests/integration.rs
  web-client/tests/wasm.rs
  zkp-circuits/src/circuits/mod.rs
  zkp-primitives/pedersen-generators/src/lib.rs
  zkp/examples/verify.rs
Labels: enhancement

#3166 Make zkp errors more informative
  zkp-component/src/proof_utils.rs
  zkp-component/src/types.rs
  zkp-component/src/zkp_requests.rs
Labels: enhancement

#3180 Remaining clippy fixes
  lib/Cargo.toml
  lib/src/extras/deadlock.rs
  lib/src/extras/launcher.rs
  lib/src/extras/mod.rs
Labels: enhancement

#3142 Add a plain list of `services` to web-client peer info structs
  web-client/example/module.js
  web-client/src/client/peer_info.rs
Labels: WASM

#3198 RPC Server: handle `create_basic_transaction_with_data` method hex decoding errors gracefully
  rpc-server/src/dispatchers/consensus.rs
Labels: bug
