Repository nimiq/core-rs-albatross, pull requests merged in 2024-03, with the labels that each got.

#1884 web-client: Add basic Merkle Tree and multisig APIs
  Cargo.lock
  primitives/transaction/src/signature_proof.rs
  web-client/Cargo.toml
  web-client/src/primitives/merkle_tree.rs
  web-client/src/primitives/mod.rs
  web-client/src/primitives/signature_proof.rs
Labels: WASM

#2281 Add the new zkp keys
  .zkp_testnet/meta_data.bin
  .zkp_testnet/verifying_keys/merger_wrapper.bin
Labels: bug

#2298 All current dependabot updates v20
  Cargo.lock
  blockchain/Cargo.toml
  mempool/Cargo.toml
  metrics-server/Cargo.toml
  network-libp2p/Cargo.toml
Labels: dependency

#2326 All current dependabot updates v22
  Cargo.lock
  database/Cargo.toml
  network-interface/Cargo.toml
  primitives/block/Cargo.toml
  primitives/transaction/Cargo.toml
Labels: dependency
