Repository nimiq/core-rs-albatross, pull requests merged in 2024-06, with the labels that each got.

#2563 Refactoring network into swarm, rate limiting and network types
  network-libp2p/src/lib.rs
  network-libp2p/src/network.rs
  network-libp2p/src/network_types.rs
  network-libp2p/src/rate_limiting.rs
  network-libp2p/src/swarm.rs
Labels: enhancement, refactor

#2536 network-libp2p: Update `kad` configuration
  network-libp2p/src/config.rs
  network-libp2p/src/lib.rs
  network-libp2p/src/swarm.rs
Labels: testnet-restart

#2585 Consistent style for network topic names
  consensus/src/messages/mod.rs
  network-libp2p/tests/network.rs
  network-mock/src/lib.rs
  primitives/block/src/block.rs
  primitives/transaction/src/lib.rs
  web-client/tests/wasm.rs
  zkp-component/src/types.rs
Labels: testnet-restart

#2618 Fix call to add_to_history in tests
  test-utils/src/test_custom_block.rs
Labels: bug

#2610 Fix revert for trie diffs to include incomplete part as well
  blockchain/src/blockchain/rebranch_utils.rs
  blockchain/tests/push_with_chunks.rs
  primitives/account/src/accounts.rs
  primitives/account/src/receipts.rs
  primitives/src/trie/trie_diff.rs
  primitives/trie/src/trie.rs
Labels: bug

#2512 Calculate a transaction's related addresses and expose them via RPC
  primitives/transaction/src/lib.rs
  rpc-interface/src/types.rs
Labels: testnet-restart

#2677 Fix eternally paused state sync and chunk ordering issues
  consensus/src/sync/live/state_queue/mod.rs
Labels: bug

#2694 Update Rust dependencies
  Cargo.lock
Labels: dependency
