Repository nimiq/core-rs-albatross, pull requests merged in 2024-10, with the labels that each got.

#2938 Improve database pruning
  blockchain/src/blockchain/accounts.rs
  blockchain/src/blockchain/history_sync.rs
  blockchain/src/chain_store.rs
Labels: enhancement

#2943 Verifying response from request block and calling cached hash
  consensus/src/consensus/head_requests.rs
  consensus/src/messages/mod.rs
  consensus/src/sync/light/sync.rs
  consensus/src/sync/live/block_queue/block_request_component.rs
  consensus/src/sync/sync_queue.rs
Labels: bug

#2929 Disambiguate VRF seeds across non-competing branches
  blockchain/src/block_production/mod.rs
  pow-migration/src/genesis.rs
  primitives/block/src/block.rs
  primitives/block/src/equivocation_proof.rs
  test-utils/src/test_custom_block.rs
  vrf/src/vrf.rs
Labels: testnet-restart

#2940 Implement pagination by tx hash for requesting of transaction history
  blockchain/src/history/history_store_index.rs
  blockchain/src/history/interface.rs
  consensus/src/consensus/consensus_proxy.rs
  consensus/src/messages/handlers.rs
  consensus/src/messages/mod.rs
  consensus/tests/consensus_proxy.rs
  rpc-client/src/subcommands/blockchain_subcommands.rs
  rpc-interface/src/blockchain.rs
  rpc-server/src/dispatchers/blockchain.rs
  web-client/src/client/lib.rs
Labels: enhancement

#2979 Wallet Store: Allow removal of an account
  rpc-interface/src/wallet.rs
  rpc-server/src/dispatchers/wallet.rs
  wallet/src/wallet_store.rs
Labels: enhancement

#2988 Remove wasm-pack build step from web-client CI job
  .github/workflows/build+test.yml
Labels: github_actions
