Repository nimiq/core-rs-albatross, pull requests merged in 2024-05, with the labels that each got.

#2377 Use argon2id by default
  hash/src/argon2kdf.rs
  hash/tests/mod.rs
  utils/src/otp.rs
Labels: enhancement

#2424 Fix merkle path generation for multisig signature proofs in web-client
  web-client/src/primitives/signature_proof.rs
Labels: bug, WASM

#2435 All current dependabot updates v28
  Cargo.lock
Labels: dependency

#2538 Fixing code coverage
  .github/workflows/code_coverage.yml
Labels: bug, github_actions

#2518 Change serialization order of KeyPair to have the private key first
  keys/src/key_pair.rs
Labels: regression
