Repository nimiq/core-rs-albatross, pull requests merged in 2024-07, with the labels that each got.

#2681 Extend transaction topic mesh to non-validator nodes
  Cargo.lock
  Cargo.toml
  blockchain-interface/src/error.rs
  client/src/main.rs
  consensus/src/consensus/consensus_proxy.rs
  consensus/src/consensus/mod.rs
  lib/Cargo.toml
  lib/src/client.rs
  lib/src/extras/rpc_server.rs
  mempool/Cargo.toml
  mempool/mempool-task/Cargo.toml
  mempool/mempool-task/src/lib.rs
  rpc-server/src/dispatchers/validator.rs
  spammer/src/main.rs
  validator/Cargo.toml
  validator/src/proposal_buffer.rs
  validator/src/validator.rs
  web-client/src/client/lib.rs
Labels: enhancement

#2700 Only treat signaling transactions as control transactions
  primitives/transaction/src/control_transaction.rs
Labels: testnet-restart

#2658 Limiting transactions sender and recipient data.
  keys/src/lib.rs
  primitives/src/policy.rs
  primitives/transaction/src/account/basic_account.rs
  primitives/transaction/src/account/htlc_contract.rs
  primitives/transaction/src/account/staking_contract/mod.rs
  primitives/transaction/src/account/staking_contract/structs.rs
  primitives/transaction/src/account/vesting_contract.rs
  primitives/transaction/src/lib.rs
  primitives/transaction/src/signature_proof.rs
  primitives/transaction/tests/serialization.rs
  primitives/transaction/tests/staking_contract_verify.rs
Labels: bug, testnet-restart

#2720 Use only primitive IEEE 754 features in supply curve calculations
  blockchain/Cargo.toml
  blockchain/tests/inherents.rs
  consensus/Cargo.toml
  handel/Cargo.toml
  primitives/Cargo.toml
  primitives/src/policy.rs
  utils/Cargo.toml
  utils/src/lib.rs
  utils/src/math.rs
  utils/src/math/exp.rs
  utils/src/math/mod.rs
  utils/src/math/pow.rs
  zkp-component/Cargo.toml
Labels: testnet-restart

#2734 Use a patched libp2p-websocket-websys crate to avoid use-after-free errors
  Cargo.lock
  Cargo.toml
  web-client/dist/nodejs/worker.js
  web-client/dist/nodejs/worker.mjs
Labels: WASM

#2762 Split code cov in 3 tasks
  .github/workflows/code_coverage.yml
Labels: bug, github_actions

#2780 Update README
  README.md
  docs/becoming_validator.md
  docs/becoming_validator_jsoncli.md
Labels: documentation

#2791 Change starting of rounds from the wrong current id to the correct given id.
  tendermint/src/tendermint.rs
Labels: bug

#2785 Fixing parallel feature for the primitives crate.
  Cargo.lock
  hash/src/lib.rs
  lib/Cargo.toml
  primitives/Cargo.toml
  primitives/src/slots_allocation.rs
  zkp-circuits/Cargo.toml
  zkp-component/Cargo.toml
  zkp-primitives/Cargo.toml
  zkp/Cargo.toml
Labels: enhancement
