Repository nimiq/core-rs-albatross, pull requests merged in 2024-11, with the labels that each got.

#3005 Make PeerContact timestamp non optional
  Cargo.lock
  lib/Cargo.toml
  lib/src/client.rs
  network-libp2p/src/discovery/peer_contacts.rs
  network-libp2p/tests/discovery.rs
  network-libp2p/tests/network.rs
  network-libp2p/tests/request_response.rs
  test-utils/Cargo.toml
  test-utils/src/test_network.rs
Labels: testnet-restart

#2997 Blockchain: add `network_id` to `SkipBlockInfo`
  blockchain/src/block_production/mod.rs
  blockchain/tests/signed.rs
  primitives/block/src/micro_block.rs
  primitives/block/src/skip_block.rs
  test-utils/src/block_production.rs
  test-utils/src/test_custom_block.rs
  validator/src/micro.rs
  validator/tests/mock.rs
Labels: testnet-restart

#3040 Force rust toolchain for web-client NPM build
  .github/workflows/npm_publish.yml
Labels: WASM

#3045 Prevent pruning pre-genesis data
  blockchain/src/blockchain/push.rs
  blockchain/src/blockchain/zkp_sync.rs
Labels: bug

#3062 Restrict Block topics from gossipsub to two blocks per second
  consensus/src/messages/mod.rs
Labels: enhancement

#3075 Fix wrongly inverted trusted flag for contributions
  handel/src/aggregation.rs
Labels: bug

#3081 NAT: Replace the state of addresses
  network-libp2p/src/autonat.rs
Labels: bug

#3095 Changing the max connections per peer so that the seed nodes become public
  network-libp2p/src/behaviour.rs
Labels: bug

#3090 Prepare web-client NPM package for the proper release
  .github/workflows/npm_publish.yml
  web-client/dist/package.json
Labels: v1

#3113 Fix size of serialized signature proof contants in web-client
  web-client/src/common/signature_proof.rs
Labels: bug

#3109 consensus: Fix transaction proofs for non finalized blocks
  consensus/src/messages/handlers.rs
Labels: bug

#3102 Deduplicate jail logs
  primitives/account/src/account/staking_contract/traits.rs
  primitives/account/src/account/staking_contract/validator.rs
  primitives/account/src/logs.rs
  primitives/account/tests/staking_contract/validator.rs
  rpc-interface/src/types.rs
Labels: bug

#3122 Avoid double-wrapping wasm libp2p transport in only_secure_ws_transport
  network-libp2p/src/swarm.rs
Labels: bug, WASM

#3139 Set pre-genesis flag before using it
  lib/src/client.rs
Labels: bug

#3143 Add more networking config options to web-client ClientConfiguration
  web-client/src/client/lib.rs
  web-client/src/common/client_configuration.rs
Labels: WASM

#3154 Improve logging for Tendermint State Update
  validator/src/aggregation/tendermint/contribution.rs
  validator/src/aggregation/tendermint/state.rs
  validator/src/validator.rs
Labels: enhancement
