Repository nimiq/core-rs-albatross, pull requests merged in 2024-02, with the labels that each got.

#2173 Remove unused `seed_message` from genesis builder
  genesis-builder/src/config.rs
  genesis-builder/src/lib.rs
  genesis/src/genesis/dev-albatross-4-validators.toml
  genesis/src/genesis/dev-albatross.toml
  genesis/src/genesis/test-albatross.toml
  genesis/src/genesis/unit-albatross.toml
  pow-migration/src/genesis/mod.rs
  scripts/devnet/templates/dev-albatross-genesis.toml.j2
Labels: testnet-restart

#2201 Adding retire balance field on rpc and webclient staker types
  rpc-interface/src/types.rs
  web-client/src/client/account.rs
Labels: bug

#2206 Fix set active stake and revert update staker
  primitives/account/src/account/staking_contract/staker.rs
  primitives/account/tests/staking_contract/mod.rs
  primitives/account/tests/staking_contract/staker.rs
Labels: bug, testnet-restart

#2189 History store also stores transaction results
  blockchain/src/blockchain/verify.rs
  blockchain/src/history/history_store.rs
  blockchain/tests/history_store.rs
  consensus/src/consensus/consensus_proxy.rs
  consensus/src/messages/handlers.rs
  consensus/tests/consensus_proxy.rs
  primitives/transaction/src/historic_transaction.rs
  primitives/transaction/src/lib.rs
Labels: bug, testnet-restart

#2239 All current dependabot updates v17
  Cargo.lock
Labels: dependency

#2259 Upgrade `portable-atomic` dependency to 1.6.0
  Cargo.lock
Labels: dependency
