Repository nimiq/core-rs-albatross, pull requests merged in 2025-03, with the labels that each got.

#3305 RPC: Make blocks' body hash non-optional, as it's always provided
  rpc-interface/src/types.rs
Labels: enhancement

#3331 web-client: Set num_initial_connections to default 4
  web-client/src/client/lib.rs
  web-client/src/common/client_configuration.rs
Labels: bug

#3340 web-client: Handle PoW `mined` transaction state
  web-client/src/common/transaction.rs
Labels: pow-compatibility

#3339 Avoid constant zkp requests
  consensus/src/consensus/mod.rs
Labels: enhancement
